### PR TITLE
Use only one contents CLI option

### LINKED ISSUE #19: Drop the JupyterLite `--contents` CLI option?
The build command now uses two ways for proving contents:

https://github.com/voila-dashboards/voici-demo/blob/0af62aeb70ecc31d7ba6a789ff11ecf82c1e162d/.github/workflows/deploy.yml#L31

From an outside perspective, it could confuse users who may not know what the differences between the two are.

Maybe we can simplify it with the following:

```yaml
 run: voici build --output-dir dist --XeusAddon.mounts content:/content 
```

### PR DESCRIPTION
**Pull request by jtpio**
Fixes https://github.com/voila-dashboards/voici-demo/issues/19

Since this demo uses the xeus python kernel, and is focused on voici, we can just for the xeus mounting feature.

cc @martinRenou this is addressing the proposal mentioned in https://github.com/voila-dashboards/voici-demo/issues/19.

Additionally, we could link to the Voici / Xeus Python documentation for working with contents.

### CODE REVIEW

**Comment by martinRenou** [comment]
Does this actually work? Will voici properly find the contents for filling the Voici tree page?

**Comment by jtpio** [comment]
Good point!

Maybe the best way forward would then be to follow the discussion started in https://github.com/voila-dashboards/voici/issues/104#issuecomment-1895383878 and try to implement that in the xeus addon.

Converting to draft for now.

**Comment by martinRenou** [comment]
Fixed by #22

**Comment by martinRenou** [comment]
Thanks!

**Pull request closed without merging**
